### ISSUE TITLE
[required] does not work on closures

### ISSUE THREAD

**Issue by BitPuffin** [boo-lang/boo#131]
``` boo
def A():
	def c([required] s as string):
		pass
```

```
booc requiredclosure.boo
Boo Compiler version 0.9.7.0 (CLR 2.0.50727.8009)
requiredclosure.boo(2,5): BCW0003: WARNING: Unused local variable 'c'.
1 warning(s).
requiredclosure.boo(2,12): BCE0015: Node '[required]' has not been correctly processed.
1 error(s).
```

**Comment by masonwheeler** [comment]
This appears to be caused by `BindAndApplyAttributes.OnBlock()`:

		override public void OnBlock(Block node)
		{
			// No need to visit blocks
		}

Apparently there is a need after all. :)

**Comment by masonwheeler** [comment]
After removing that, this specific case still fails due to the following code in `RequiredAttribute`:

	private def TargetMethod(parameter as ParameterDeclaration):
		method = parameter.ParentNode as Method
		return method if method is not null
		
		property = parameter.ParentNode as Property
		CheckProperty property
		return property.Setter
		
	private def CheckProperty(property as Property):
		if property is null or property.Setter is null:
			InvalidNodeForAttribute('ParameterDeclaration or Property')
		
This attribute expects to be placed on a `ParameterDeclaration` for a `Method`, or on a `Property` for which it can extract a Setter `Method`.  It doesn't know how to deal with a `ParameterDeclaration` on a `BlockExpression`.

What it actually needs, though, is not a `Method`, but the `Block` that represents the method's body.  Fixing this too.

**Comment by masonwheeler** [comment]
Found that the same problem exists on `RequiredAttribute`.  Fixing it there as well.

**Comment by BitPuffin** [comment]
Awesome, nice work. I was considering looking into it myself as it seemed like a pretty approachable bug. But thanks for saving me the trouble! :)
