### ISSUE TITLE
booi.exe CommandLine always IsValid

### ISSUE THREAD

**Issue by fernandolguevara** [boo-lang/boo#174]
if booi is executed without parameters never shows the"usage help"
```boo
if not cmdline.IsValid or cmdline.DoHelp:
        print "Usage: booi [options] <script|-> [-- [script options]]"
        print "Options:"
        cmdline.PrintOptions(Console.Out)
        return Program.DefaultErrorCode
```
https://github.com/boo-lang/boo/blob/master/src/booi/CommandLine.boo#L25

**Comment by masonwheeler** [comment]
@bamboo He's right; `IsValid` is hardcoded to return `true`.  Any idea what the rationale is here?  I suspect this was meant to do something that was left unfinished?

**Comment by fernandolguevara** [comment]
@bamboo

**Comment by bamboo** [comment]
No idea.

**Comment by masonwheeler** [comment]
@fernandolguevara All right.  So we've got a hard-coded, non-virtual value with no way to change it, and no rationale for it.

So if I understand it, the problem is that you want to see the usage help if you simply type `booi` with no arguments on the command line, and it ends up not printing anything?

This can probably be fixed, but I'd have to look at how the `AbstractCommandLine` base class is implemented.

**Comment by masonwheeler** [comment]
It looks like `IsValid` is meaningless, as the command-line parser will raise an exception if you pass an unrecognized argument.

I think I need to fix this by implementing an `IsEmpty` property and using that here instead of `IsValid`.  I'll do that later on today.

**Comment by masonwheeler** [comment]
OK, that should fix it. :)
