### ISSUE TITLE
How to cal win32 API functions from Boo ?

### ISSUE THREAD

**Issue by vinodvinu** [boo-lang/boo#175]
Hi, I like Boo. It's a nice language. But i am trying to call some win 32 api functions (like ShowWindow, FindWindow, SendMessage, etc etc...) from my Boo class. How can i do it. Any tutorials ?.

**Comment by masonwheeler** [comment]
[Here's an example.](https://github.com/masonwheeler/TURBU/blob/3e6e875f9a6bacd5fcc694dd92b27f914af4eabe/TURBU.EngineBasis/FTGL.boo)

It's essentially done the same way as in C#, except that there's no need for an `extern` keyword because the compiler automagically recognizes the `DllImport` attribute.

**Comment by vinodvinu** [comment]
Hi masonwheeler, 
Thanks a lot.  Let me try it. I would like to learn more about Boo. Is there any forum for Boo programmers ?

**Comment by masonwheeler** [comment]
The official discussion forum for the language is at https://groups.google.com/forum/#!forum/boolang

**Comment by coremanster** [comment]
this website is good help for c#, and presumably boo, for calling win32 functions 
https://pinvoke.net/
