### ISSUE TITLE
Compiled Boo Distribution

### ISSUE THREAD

**Issue by DaMammoth42** [boo-lang/boo#213]
Is there a way I can get a already compiled version? The compiler that is required doesn't work on my computer, and neither do any of the other binaries. Where would I acquire a compiled boo distribution? Please don't tell me to compile it myself, if I wanted to (or could), I would.

**Comment by DaMammoth42** [comment]
Also, the errors I have been getting are from the booc, booi, and booish. I have a Windows 10 computer. The error I get from Sharp Develop is: `Unable to load assembly (bad file format): WRN: Assembly binding logging is turned OFF. (BCE0000)`.

**Comment by DaMammoth** [comment]
Why do you need to compile everything yourself on Github? Is it because people want to act smart? Nobody CARES what the source is, they just want the finished product. Source is pointless. You don't need it, and you shouldn't want it. Nobody is going to say: "Hey, I might just look at this source code and upgrade it", That's the developers job. A *lazy* developer would ask everyone else to do the work for them.

**Comment by masonwheeler** [comment]
It's because this is a small project without the resources of a major multinational corporation backing it.  All that polish takes time and work.

If you need a prebuilt distribution, you can grab the latest Unstable build from the [Releases page.](https://github.com/boo-lang/boo/releases)
